//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class logistic_patch_ca {
  public static SWIGTYPE_p_double logistic_patch_ca1(double a0, double a1, int moor_neighbour_size, double t_spontaneous, double sigma, int height, int width, SWIGTYPE_p_double initial_data, SWIGTYPE_p_double pg_data, SWIGTYPE_p_double suitable_data, int area_all, bool show_img) {
    global::System.IntPtr cPtr = logistic_patch_caPINVOKE.logistic_patch_ca(a0, a1, moor_neighbour_size, t_spontaneous, sigma, height, width, SWIGTYPE_p_double.getCPtr(initial_data), SWIGTYPE_p_double.getCPtr(pg_data), SWIGTYPE_p_double.getCPtr(suitable_data), area_all, show_img);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

}
