//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class simple_ca {
  public static SWIGTYPE_p_double simple_ca_logistic(SWIGTYPE_p_double p_2001_img, SWIGTYPE_p_double p_land, SWIGTYPE_p_double p_pg, int width, int height, double transfer_threshold, int times) {
    global::System.IntPtr cPtr = simple_caPINVOKE.simple_ca_logistic(SWIGTYPE_p_double.getCPtr(p_2001_img), SWIGTYPE_p_double.getCPtr(p_land), SWIGTYPE_p_double.getCPtr(p_pg), width, height, transfer_threshold, times);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public static double testArray(SWIGTYPE_p_double a) {
    double ret = simple_caPINVOKE.testArray(SWIGTYPE_p_double.getCPtr(a));
    return ret;
  }

  public static int draw_image(SWIGTYPE_p_double img_buffer, int width, int height) {
    int ret = simple_caPINVOKE.draw_image(SWIGTYPE_p_double.getCPtr(img_buffer), width, height);
    return ret;
  }

}
